### PR TITLE
Adding vadapav.mov scraper using BeautifulSoup4

### PR DESCRIPTION
**Pull request by gijocode**

### CODE REVIEW

**Comment by r3tr0ananas** [comment]
Could you please reformat the code to make it more easier to read?

Also, why did you add a resolution extractor if the resolution will be handled by mov-cli?

**Comment by gijocode** [comment]
> Could you please reformat the code to make it more easier to read?
> 
> Also, why did you add a resolution extractor if the resolution will be handled by mov-cli?

I have reformatted it with black.

In vadapav.mov, some movie folders contain different files for the same movie. Usually they differ in resolution. For example: [Novel Romance](https://vadapav.mov/f5349cb7-9a20-4970-8ed2-9ef290b5a7d9/)

When mov-cli queries for a movie link, we are only allowed to send back a single url for said movie. Hence I am determining the best quality to return back the best url

**Comment by THEGOLDENPRO** [comment]
> Also, why did you add a resolution extractor if the resolution will be handled by mov-cli?

This is alright, I will allow the scraper to also handle the resolution. We can use scraper options to pass the resolution configured in mov-cli directly to the scraper.

**Comment by THEGOLDENPRO** [comment]
Nice work, I'm gonna make some small adjustments and port this scraper over to mov-cli v4.3.

**Comment by THEGOLDENPRO** [comment]
@gijocode Thanks a lot for your pull request btw ✨

**Comment by gijocode** [comment]
> @gijocode also would you like to become a contributor of the films plugin by any chance? We are currently on the lookout for contributors.

What will i have to do if I'm a contributor?

**Comment by r3tr0ananas** [comment]
> > @gijocode also would you like to become a contributor of the films plugin by any chance? We are currently on the lookout for contributors.
> 
> What will i have to do if I'm a contributor?

for example: fixing bugs, adding new sites (If you want)

**Comment by gijocode** [comment]
> for example: fixing bugs, adding new sites (If you want).

I'm totally down to help out with bugs and enhancements whenever I've got some free time, but I don't want to get too tied up in it. Just want to chip in when I can!

**Pull request merged**
